spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_portalcursos
    username: root
    password: tu_nueva_contraseña
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # valida contra tablas ya creadas
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080